CREATE TABLE "GCG_6071_LZ_TRUEVW" (
 "EMPLOYEE" CHAR(5),
 "EMPLOYEENAME" CHAR(30),
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "DEPT_EMPLOYEE" CHAR(4),
 "CREATED" DATETIME DEFAULT NOW(),
 "TIME_ELAPSED" INTEGER,
 "NOTIFY" INTEGER DEFAULT '0' NOT NULL,
 "NOTIFY_EMAIL" CHAR(200),
 "STATUS" CHAR(50),
 "DESCRIPTION" CHAR(30) );